### ISSUE TITLE
Addressing Part 2 Feedback

### ISSUE THREAD

**Issue by k----n** [md6113/404cmputProject#116]
- [x] Make image posts return base64 and content-type in API
- [x] Make trusted field in node model more logical
- [x] Change API to spec
- [x] Make allow posts, allow images field in node model
- [x] Delete posts and users tied to node if node is deleted

**Comment by omokdad** [comment]
To change the api to match the other teams, we need to:

* Images are exclusive in a post, sent over base64 as the content and image/base64 as content type.

* Change the sending and accepting of author id's (including redirects, etc.) (DONE)

* Check if person is still friend every time you visit profile

* In /api/posts, change "results" to "posts" (DONE)
