### ISSUE TITLE
16 - US: As an author, I want to pull in my github activity to my “stream”

### ISSUE THREAD

**Issue by genomaxx** [md6113/404cmputProject#16]
- [ ] Write Documentation 
- [ ] Production 
- [ ] Tests

**Comment by md6113** [comment]
Write the documentation - [ ]

**Comment by k----n** [comment]
https://developer.github.com/v3/activity/events/types/

https://api.github.com/users/:user/events

**Comment by k----n** [comment]
http://tinysort.sjeiti.com/
