### ISSUE TITLE
25 - US: As a server admin, I want to be able add, modify, and remove authors.

### ISSUE THREAD

**Issue by genomaxx** [md6113/404cmputProject#25]
- [x] Production

**Comment by iameric1986** [comment]
We can just use the Django admin built-in for this right? This is doable right now. Should we close this issue?

**Comment by k----n** [comment]
Seems to meet requirements?

**Comment by emmettu** [comment]
I agree but will ask on the forum or in class tomorrow.

**Comment by k----n** [comment]
Josh said it was fine
